name: Test and Deploy

on:
  push:
    branches:
      - dev

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Install dependencies
        run: mvn dependency:resolve
      - name: Run tests
        run: mvn test -DsuiteXmlFile=src/test/java/suites/login.xml
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Auto-commit changes
        run: |
          git config --global user.email "github-bot@example.com"
          git config --global user.name "GitHub Bot"
          git commit -am "Auto-commit changes"
          git push
      - name: Pull changes to staging
        if: ${{ success() }}
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Merge changes from dev to staging"
          branch: staging
          title: "Merge changes from dev to staging"
          body: |
            This is an automated pull request to merge changes from the dev branch to the staging branch.
