name: Test and Deploy

on:
  push:
    branches:
      - dev

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Install dependencies
        run: mvn dependency:resolve
      - name: Run tests
        run: mvn test -DsuiteXmlFile=src/test/java/suites/login.xml
      - name: Commit test reports
        if: ${{ success() }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add target/surefire-reports
          git commit -m "Add test reports"
      - name: Push changes to staging
        if: ${{ success() }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Merge changes from dev to staging branch"
          commit_options: "--no-verify"
          branch: staging
          file_pattern: .
          pull_branch: dev
